### ISSUE TITLE
[Feature request] Make it more powerful

### ISSUE THREAD

**Issue by BachiMjavanadze** [Angelmaneuver/command-launcher#2]
I have been looking for a normal extension for the terminal for a long time but did not find it. [Script Runner](https://marketplace.visualstudio.com/items?itemName=easterapps.script-runner) suits my needs more or less. I wrote to the author what needs to be corrected and added, but he does not answer. Can you please look at my [feature requests](https://github.com/easterapps/vscode-script-runner/issues) and add them to your extension?

Here is my settings (in `settings.json`) for the `Script Runner` (I'm on Windows, commands are for `cmd` or `powershell`):

` 
"script-runner.statusBar": true,
 "script-runner.definitions": {
    "variables": {
      "$path": "D:\\Documents\\Development",
    },
    "commands": [
      {
        "identifier": "Angular 1",
        "description": "Angular - create project + ESlint + CSS",
        "command": "ng new $var1 --style=css --routing=false; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          }
        ]
      },
      {
        "identifier": "Angular 2",
        "description": "Angular - create project + ESlint + CSS + Routing",
        "command": "ng new $var1 --style=css --routing=true; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          }
        ]
      },
      {
        "identifier": "Angular 3",
        "description": "Angular - create project + ESlint + SCSS",
        "command": "ng new $var1 --style=scss --routing=false; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          }
        ]
      },
      {
        "identifier": "Angular 4",
        "description": "Angular - create project + ESlint + SCSS  + Routing",
        "command": "ng new $var1 --style=scss --routing=true; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          }
        ]
      },
      {
        "identifier": "Angular 5",
        "description": "Angular - create project (interactive mode)",
        "command": "ng new $var1 --style=$var2 --routing=$var3; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          },
          {
            "variable": "$var2",
            "question": "CSS or SCSS?",
            "options": [
              "css",
              "scss"
            ]
          },
          {
            "variable": "$var3",
            "question": "Install roating?",
            "options": [
              "true",
              "false"
            ]
          }
        ]
      },
      {
        "identifier": "C# - console",
        "description": "C# - create new console project",
        "command": "dotnet new console -o $var1; cd $var1; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          }
        ]
      },
      {
        "identifier": "C# - asp.net",
        "description": "C# - create new asp.net",
        "command": "dotnet new web -o $var1; cd $var1; code -r .",
        "working_directory": "$path",
        "form": [
          {
            "variable": "$var1",
            "question": "Project name"
          }
        ]
      }
    ]
  },
`

**Comment by Angelmaneuver** [comment]
Hi BachiMjavanadze.
I'll answer for your feature request.

In conclusion, your feature request is rejected.
The reason is that it takes time and effort, but I do not feel attractive.

1. [[Feature request] Group commands #15](https://github.com/easterapps/vscode-script-runner/issues/15)
I believe this functionality requirement can be met by creating a folder and creating commands under it.

1. [[Feature request] Contex menu commands #16](https://github.com/easterapps/vscode-script-runner/issues/16)
I think the request is to switch the content of the command for each folder path, but if the project changes, the folder structure will also change.
Also, I think there is a pattern where the folder path is the same but the language is different.
Frankly, it's a pain to think about.
I think it would be easier to create a folder for each category and have a set of commands.

1. [[Feature request] Form options object #17](https://github.com/easterapps/vscode-script-runner/issues/17)
I did not understand the content of the request, but it seems that vscode-script-runner can dynamically assembule command contents in an interactive manner, so I guess it is a request related to that.
This extension does not have that feature.
This extension can be configured to just paste the command into the terminal instead of executing it on a command-by-command basis.
If necessary, you can edit and run the command pasted into the terminal.
Frankly, it is lame, but I don't think it is much of a problem for practical use.

We apologize for not meeting your expectations.

Thanks for reporting the issue.
If there are no additional questions, I'll close this issue in about week.

**Comment by BachiMjavanadze** [comment]
No more questions. Close it
