### ISSUE TITLE
[Feature request] Last executed command from command launcher

### ISSUE THREAD

**Issue by AdmiralRazorbeard** [Angelmaneuver/command-launcher#3]
Hi,

As Command launcher became my primarily way to execute commands with Vscode, I would find handy to have to possibility to have the last executed command from Command launcher listed always on top of the Command launcher list (for easy access).

This isn't an essential feature but I think it would still be handy
I'm currently writing an extension of my own (to manipulate files) and if you're not interested in developing this suggestion, I may at some point in the future develop that feature and create a pull request . Would that be a feature you may accept for your extension in the future ?

Thanks

**Comment by Angelmaneuver** [comment]
Hi AdmiralRazorbeard ~~Hi BachiMjavanadze.~~ Oh...Sorry...
I'll answer for your feature request and question.

In conclusion, your feature request and pull request is rejected.
Both reasons are due to the test code.

The test code was also the reason for the rejected of the previous feature request.
It saddens me to say this, but the test code in this repository is terrible.
It takes the same amount of time as implementation, maybe even more.

But we also consider it important because of the frequency of VSCode's upgrade and the variety of operations.

If you are going to submit a pull request, test code is a must.
But it will be impossible. I am sure of it, I am sick of it.

Thanks for reporting the issue.
If there are no additional questions, I'll close this issue in about week.

**Comment by AdmiralRazorbeard** [comment]
Ok no problem 👍

(I'm not BachiMjavanadze even though I wrote [Feature request] the same way ^^)
